### ISSUE TITLE
jdk16-windows-aarch64-hotspot connection lost: JNLP4-connect connection from host109-150-95-16

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/temurin-build#2496]
https://ci.adoptopenjdk.net/job/build-scripts/job/utils/job/cross-compiled-version-out/136/console
```
02:02:02  test-gdams-win10-aarch64-1 was marked offline: Connection was broken: java.nio.channels.ClosedChannelException
02:02:02  	at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer.onReadClosed(ChannelApplicationLayer.java:209)
02:02:02  	at org.jenkinsci.remoting.protocol.ApplicationLayer.onRecvClosed(ApplicationLayer.java:221)
02:02:02  	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecvClosed(ProtocolStack.java:816)
02:02:02  	at org.jenkinsci.remoting.protocol.FilterLayer.onRecvClosed(FilterLayer.java:288)
02:02:02  	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.onRecvClosed(SSLEngineFilterLayer.java:181)
02:02:02  	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.switchToNoSecure(SSLEngineFilterLayer.java:283)
02:02:02  	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processWrite(SSLEngineFilterLayer.java:503)
02:02:02  	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processQueuedWrites(SSLEngineFilterLayer.java:248)
02:02:02  	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.doSend(SSLEngineFilterLayer.java:200)
02:02:02  	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.doCloseSend(SSLEngineFilterLayer.java:213)
02:02:02  	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.doCloseSend(ProtocolStack.java:784)
02:02:02  	at org.jenkinsci.remoting.protocol.ApplicationLayer.doCloseWrite(ApplicationLayer.java:172)
02:02:02  	at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer$ByteBufferCommandTransport.closeWrite(ChannelApplicationLayer.java:314)
02:02:02  	at hudson.remoting.Channel.close(Channel.java:1502)
02:02:02  	at hudson.remoting.Channel.close(Channel.java:1455)
02:02:02  	at hudson.slaves.SlaveComputer.closeChannel(SlaveComputer.java:874)
02:02:02  	at hudson.slaves.SlaveComputer.access$100(SlaveComputer.java:110)
02:02:02  	at hudson.slaves.SlaveComputer$2.run(SlaveComputer.java:765)
02:02:02  	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
02:02:02  	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
02:02:02  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
02:02:02  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
02:02:02  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
02:02:02  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
02:02:02  	at java.lang.Thread.run(Thread.java:823)
Also:   hudson.model.Computer$TerminationRequest: Termination requested at Wed Feb 10 12:34:50 CET 2021 by Thread[Ping thread for channel hudson.remoting.Channel@ba4f6642:JNLP4-connect connection from host109-150-95-16.range109-150.btcentralplus.com/109.150.95.16:62850,5,main] [id=95599]
		at hudson.model.Computer.recordTermination(Computer.java:229)
		at hudson.model.Computer.disconnect(Computer.java:495)
		at hudson.slaves.SlaveComputer.disconnect(SlaveComputer.java:759)
		at hudson.slaves.ChannelPinger$1.onDead(ChannelPinger.java:195)
		at hudson.remoting.PingThread.ping(PingThread.java:134)
		at hudson.remoting.PingThread.run(PingThread.java:90)
```

**Comment by andrew-m-leonard** [comment]
builds disabled now
