### ISSUE TITLE
Missing ECDHE Ciphers in 8-jdk-alpine

### ISSUE THREAD

**Issue by darkedges** [adoptium/temurin-build#2963]
**What are you trying to do?**
Connect to an nginx server with SSL enabled.

**Expected behaviour:**
I am able to connect to the instance

**Observed behaviour:**
I am getting a handshake alert due to missing ECDHE ciphers.

**Any other comments:**
Non Alpine instance of `8u332-b09-jdk` shows 45 Ciphers
```
C:\Users\nirvi>docker run -it eclipse-temurin:8u332-b09-jdk sh
Unable to find image 'eclipse-temurin:8u332-b09-jdk' locally
8u332-b09-jdk: Pulling from library/eclipse-temurin
125a6e411906: Pull complete
42222acc001c: Pull complete
aa599c547282: Pull complete
4f9cb418aceb: Pull complete
Digest: sha256:f9e4c3530ed9b02b7253f03f7ef0f2a119dbf65226c3dbc1670474058a23f444
Status: Downloaded newer image for eclipse-temurin:8u332-b09-jdk
root@4dc19fef0c58:/tmp# apt-get update
root@4dc19fef0c58:/tmp# apt-get install vim
root@4dc19fef0c58:/tmp# vi PrintCiphers.java
root@4dc19fef0c58:/tmp# javac PrintCiphers.java
root@4dc19fef0c58:/tmp# java PrintCiphers
SSLServerSocketFactory -> sun.security.ssl.SSLServerSocketFactoryImpl
1 TLS_AES_256_GCM_SHA384
2 TLS_AES_128_GCM_SHA256
3 TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
4 TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
5 TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
6 TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
7 TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
8 TLS_DHE_DSS_WITH_AES_256_GCM_SHA384
9 TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
10 TLS_DHE_DSS_WITH_AES_128_GCM_SHA256
11 TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
12 TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
13 TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
14 TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
15 TLS_DHE_RSA_WITH_AES_256_CBC_SHA256
16 TLS_DHE_DSS_WITH_AES_256_CBC_SHA256
17 TLS_DHE_RSA_WITH_AES_128_CBC_SHA256
18 TLS_DHE_DSS_WITH_AES_128_CBC_SHA256
19 TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384
20 TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384
21 TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256
22 TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256
23 TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384
24 TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384
25 TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256
26 TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256
27 TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
28 TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
29 TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
30 TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
31 TLS_DHE_RSA_WITH_AES_256_CBC_SHA
32 TLS_DHE_DSS_WITH_AES_256_CBC_SHA
33 TLS_DHE_RSA_WITH_AES_128_CBC_SHA
34 TLS_DHE_DSS_WITH_AES_128_CBC_SHA
35 TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA
36 TLS_ECDH_RSA_WITH_AES_256_CBC_SHA
37 TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA
38 TLS_ECDH_RSA_WITH_AES_128_CBC_SHA
39 TLS_RSA_WITH_AES_256_GCM_SHA384
40 TLS_RSA_WITH_AES_128_GCM_SHA256
41 TLS_RSA_WITH_AES_256_CBC_SHA256
42 TLS_RSA_WITH_AES_128_CBC_SHA256
43 TLS_RSA_WITH_AES_256_CBC_SHA
44 TLS_RSA_WITH_AES_128_CBC_SHA
45 TLS_EMPTY_RENEGOTIATION_INFO_SCSV
root@4dc19fef0c58:/tmp# exit
exit
# exit
```
Alpine instance of `8u332-b09-jdk` shows 21 Ciphers
```
C:\Users\nirvi>docker run -it eclipse-temurin:8u332-b09-jdk-alpine sh
/ # apk add bash
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/community/x86_64/APKINDEX.tar.gz
(1/4) Installing ncurses-terminfo-base (6.3_p20211120-r0)
(2/4) Installing ncurses-libs (6.3_p20211120-r0)
(3/4) Installing readline (8.1.1-r0)
(4/4) Installing bash (5.1.16-r0)
Executing bash-5.1.16-r0.post-install
Executing busybox-1.34.1-r5.trigger
OK: 12 MiB in 21 packages
/ # bash
bash-5.1# apk add vim
(1/3) Installing xxd (8.2.4836-r0)
(2/3) Installing lua5.3-libs (5.3.6-r1)
(3/3) Installing vim (8.2.4836-r0)
Executing busybox-1.34.1-r5.trigger
OK: 40 MiB in 24 packages
bash-5.1# cd /tmp/
bash-5.1# vi PrintCiphers.java
bash-5.1# javac PrintCiphers.java
bash-5.1# java PrintCiphers
SSLServerSocketFactory -> sun.security.ssl.SSLServerSocketFactoryImpl
1 TLS_AES_256_GCM_SHA384
2 TLS_AES_128_GCM_SHA256
3 TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
4 TLS_DHE_DSS_WITH_AES_256_GCM_SHA384
5 TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
6 TLS_DHE_DSS_WITH_AES_128_GCM_SHA256
7 TLS_DHE_RSA_WITH_AES_256_CBC_SHA256
8 TLS_DHE_DSS_WITH_AES_256_CBC_SHA256
9 TLS_DHE_RSA_WITH_AES_128_CBC_SHA256
10 TLS_DHE_DSS_WITH_AES_128_CBC_SHA256
11 TLS_DHE_RSA_WITH_AES_256_CBC_SHA
12 TLS_DHE_DSS_WITH_AES_256_CBC_SHA
13 TLS_DHE_RSA_WITH_AES_128_CBC_SHA
14 TLS_DHE_DSS_WITH_AES_128_CBC_SHA
15 TLS_RSA_WITH_AES_256_GCM_SHA384
16 TLS_RSA_WITH_AES_128_GCM_SHA256
17 TLS_RSA_WITH_AES_256_CBC_SHA256
18 TLS_RSA_WITH_AES_128_CBC_SHA256
19 TLS_RSA_WITH_AES_256_CBC_SHA
20 TLS_RSA_WITH_AES_128_CBC_SHA
21 TLS_EMPTY_RENEGOTIATION_INFO_SCSV
```

PrintCipher.java
```
import java.lang.reflect.Method;

import javax.net.ServerSocketFactory;

public class PrintCiphers {
	public static void main(String[] args) {
		ServerSocketFactory sslSocketFactory = javax.net.ssl.SSLServerSocketFactory.getDefault();
		System.out.println("SSLServerSocketFactory -> " + sslSocketFactory.getClass().getName());
		try {
			Method getSupportedCipherSuitesMethod = sslSocketFactory.getClass().getMethod("getSupportedCipherSuites");
			String[] ciphers = (String[]) getSupportedCipherSuitesMethod.invoke(sslSocketFactory);
			int i = 1;
			for (String c : ciphers) {
				System.out.println(i++ + " " + c);
			}
		} catch (Throwable t) {
			t.printStackTrace();
		}
	}
}
```

```

bash-5.1# java -Djdk.tls.namedGroups='secp256r1, secp384r1, secp521r1'  -Djavax.net.debug=ssl:handshake:verbose TestSSL
javax.net.ssl|FINE|01|main|2022-06-01 23:32:31.527 GMT|SSLCipher.java:438|jdk.tls.keyLimits:  entry = AES/GCM/NoPadding KeyUpdate 2^37. AES/GCM/NOPADDING:KEYUPDATE = 137438953472
javax.net.ssl|FINE|01|main|2022-06-01 23:32:31.779 GMT|Utilities.java:73|the previous server name in SNI (type=host_name (0), value=staffaccess.localdev.ciam.dlt.dev.asx.idaas.xyz) was replaced with (type=host_name (0), value=staffaccess.localdev.ciam.dlt.dev.asx.idaas.xyz)
javax.net.ssl|FINE|01|main|2022-06-01 23:32:31.812 GMT|SSLExtensions.java:260|Ignore, context unavailable extension: status_request
javax.net.ssl|FINE|01|main|2022-06-01 23:32:31.812 GMT|SupportedGroupsExtension.java:835|Ignore inactive or disabled named group: secp256r1
javax.net.ssl|FINE|01|main|2022-06-01 23:32:31.812 GMT|SupportedGroupsExtension.java:835|Ignore inactive or disabled named group: secp384r1
javax.net.ssl|FINE|01|main|2022-06-01 23:32:31.813 GMT|SupportedGroupsExtension.java:835|Ignore inactive or disabled named group: secp521r1
javax.net.ssl|WARNING|01|main|2022-06-01 23:32:31.813 GMT|SupportedGroupsExtension.java:842|no available named group
javax.net.ssl|FINE|01|main|2022-06-01 23:32:31.813 GMT|SSLExtensions.java:260|Ignore, context unavailable extension: supported_groups
javax.net.ssl|FINE|01|main|2022-06-01 23:32:31.813 GMT|ECPointFormatsExtension.java:195|Need no ec_point_formats extension
javax.net.ssl|FINE|01|main|2022-06-01 23:32:31.813 GMT|SSLExtensions.java:260|Ignore, context unavailable extension: ec_point_formats
javax.net.ssl|WARNING|01|main|2022-06-01 23:32:31.814 GMT|SignatureScheme.java:297|Signature algorithm, ed25519, is not supported by the underlying providers
javax.net.ssl|WARNING|01|main|2022-06-01 23:32:31.814 GMT|SignatureScheme.java:297|Signature algorithm, ed448, is not supported by the underlying providers
javax.net.ssl|ALL|01|main|2022-06-01 23:32:31.818 GMT|SignatureScheme.java:373|Ignore unsupported signature scheme: ed25519
javax.net.ssl|ALL|01|main|2022-06-01 23:32:31.818 GMT|SignatureScheme.java:373|Ignore unsupported signature scheme: ed448
javax.net.ssl|ALL|01|main|2022-06-01 23:32:31.818 GMT|SignatureScheme.java:373|Ignore unsupported signature scheme: ecdsa_secp256r1_sha256
javax.net.ssl|ALL|01|main|2022-06-01 23:32:31.818 GMT|SignatureScheme.java:373|Ignore unsupported signature scheme: ecdsa_secp384r1_sha384
javax.net.ssl|ALL|01|main|2022-06-01 23:32:31.818 GMT|SignatureScheme.java:373|Ignore unsupported signature scheme: ecdsa_secp521r1_sha512
javax.net.ssl|ALL|01|main|2022-06-01 23:32:31.819 GMT|SignatureScheme.java:373|Ignore unsupported signature scheme: ecdsa_sha224
javax.net.ssl|ALL|01|main|2022-06-01 23:32:31.820 GMT|SignatureScheme.java:373|Ignore unsupported signature scheme: ecdsa_sha1
javax.net.ssl|ALL|01|main|2022-06-01 23:32:31.820 GMT|SignatureScheme.java:393|Ignore disabled signature scheme: rsa_md5
javax.net.ssl|INFO|01|main|2022-06-01 23:32:31.821 GMT|AlpnExtension.java:178|No available application protocols
javax.net.ssl|FINE|01|main|2022-06-01 23:32:31.821 GMT|SSLExtensions.java:260|Ignore, context unavailable extension: application_layer_protocol_negotiation
javax.net.ssl|FINE|01|main|2022-06-01 23:32:31.821 GMT|SSLExtensions.java:260|Ignore, context unavailable extension: status_request_v2
javax.net.ssl|FINE|01|main|2022-06-01 23:32:31.822 GMT|SSLExtensions.java:260|Ignore, context unavailable extension: renegotiation_info
javax.net.ssl|FINE|01|main|2022-06-01 23:32:31.823 GMT|ClientHello.java:575|Produced ClientHello handshake message (
"ClientHello": {
  "client version"      : "TLSv1.2",
  "random"              : "57 3F CD 38 4A 11 74 17 75 E5 CA CD D6 FB D8 3B 5D 60 6B A9 36 93 20 B1 CE E2 62 E1 A3 0E B1 59",
  "session id"          : "",
  "cipher suites"       : "[TLS_DHE_RSA_WITH_AES_256_GCM_SHA384(0x009F), TLS_DHE_DSS_WITH_AES_256_GCM_SHA384(0x00A3), TLS_DHE_RSA_WITH_AES_128_GCM_SHA256(0x009E), TLS_DHE_DSS_WITH_AES_128_GCM_SHA256(0x00A2), TLS_DHE_RSA_WITH_AES_256_CBC_SHA256(0x006B), TLS_DHE_DSS_WITH_AES_256_CBC_SHA256(0x006A), TLS_DHE_RSA_WITH_AES_128_CBC_SHA256(0x0067), TLS_DHE_DSS_WITH_AES_128_CBC_SHA256(0x0040), TLS_DHE_RSA_WITH_AES_256_CBC_SHA(0x0039), TLS_DHE_DSS_WITH_AES_256_CBC_SHA(0x0038), TLS_DHE_RSA_WITH_AES_128_CBC_SHA(0x0033), TLS_DHE_DSS_WITH_AES_128_CBC_SHA(0x0032), TLS_RSA_WITH_AES_256_GCM_SHA384(0x009D), TLS_RSA_WITH_AES_128_GCM_SHA256(0x009C), TLS_RSA_WITH_AES_256_CBC_SHA256(0x003D), TLS_RSA_WITH_AES_128_CBC_SHA256(0x003C), TLS_RSA_WITH_AES_256_CBC_SHA(0x0035), TLS_RSA_WITH_AES_128_CBC_SHA(0x002F), TLS_EMPTY_RENEGOTIATION_INFO_SCSV(0x00FF)]",
  "compression methods" : "00",
  "extensions"          : [
    "server_name (0)": {
      type=host_name (0), value=staffaccess.localdev.ciam.dlt.dev.asx.idaas.xyz
    },
    "signature_algorithms (13)": {
      "signature schemes": [rsa_pss_rsae_sha256, rsa_pss_rsae_sha384, rsa_pss_rsae_sha512, rsa_pss_pss_sha256, rsa_pss_pss_sha384, rsa_pss_pss_sha512, rsa_pkcs1_sha256, rsa_pkcs1_sha384, rsa_pkcs1_sha512, dsa_sha256, rsa_sha224, dsa_sha224, rsa_pkcs1_sha1, dsa_sha1]
    },
    "signature_algorithms_cert (50)": {
      "signature schemes": [rsa_pss_rsae_sha256, rsa_pss_rsae_sha384, rsa_pss_rsae_sha512, rsa_pss_pss_sha256, rsa_pss_pss_sha384, rsa_pss_pss_sha512, rsa_pkcs1_sha256, rsa_pkcs1_sha384, rsa_pkcs1_sha512, dsa_sha256, rsa_sha224, dsa_sha224, rsa_pkcs1_sha1, dsa_sha1]
    },
    "extended_master_secret (23)": {
      <empty>
    },
    "supported_versions (43)": {
      "versions": [TLSv1.2]
    }
  ]
}
)
javax.net.ssl|FINE|01|main|2022-06-01 23:32:31.826 GMT|Alert.java:238|Received alert message (
"Alert": {
  "level"      : "fatal",
  "description": "handshake_failure"
}
)
javax.net.ssl|SEVERE|01|main|2022-06-01 23:32:31.828 GMT|TransportContext.java:316|Fatal (HANDSHAKE_FAILURE): Received fatal alert: handshake_failure (
"throwable" : {
  javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
        at sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at sun.security.ssl.Alert.createSSLException(Alert.java:117)
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:311)
        at sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
        at sun.security.ssl.TransportContext.dispatch(TransportContext.java:185)
        at sun.security.ssl.SSLTransport.decode(SSLTransport.java:152)
        at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1397)
        at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1305)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:440)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:197)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1572)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1500)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
        at TestSSL.main(TestSSL.java:25)}

)
javax.net.ssl|FINE|01|main|2022-06-01 23:32:31.829 GMT|SSLSocketImpl.java:1615|close the underlying socket
javax.net.ssl|FINE|01|main|2022-06-01 23:32:31.829 GMT|SSLSocketImpl.java:1634|close the SSL connection (initiative)
Exception in thread "main" javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
        at sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at sun.security.ssl.Alert.createSSLException(Alert.java:117)
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:311)
        at sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
        at sun.security.ssl.TransportContext.dispatch(TransportContext.java:185)
        at sun.security.ssl.SSLTransport.decode(SSLTransport.java:152)
        at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1397)
        at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1305)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:440)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:197)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1572)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1500)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
        at TestSSL.main(TestSSL.java:25)
```

**Comment by darkedges** [comment]
I have moved over to https://hub.docker.com/r/azul/zulu-openjdk-alpine to resolve this issue till such a time that I can move back to this version.

**Comment by tunggad** [comment]
> I have moved over to https://hub.docker.com/r/azul/zulu-openjdk-alpine to resolve this issue till such a time that I can move back to this version.

confirmed that moving to zulu-openjdk-alpine helps! In my case with base image eclipse-temurin:8u472-b08-jdk-alpine-3.23 the app got ssl handshake failure while calling Open AI API, probably due to missing cipher suite. Thanks!

**Comment by karianna** [comment]
Odd that we have different ciphers for Alpine than x86-64, worth a look.

**Comment by judovana** [comment]
Can the isisue be in the container, rather then in packed JDK? Or maybe build on alpine is tempting with  java.security? @tunggad  Can you diff the java.security file on your alpine and your intel?
