### ISSUE TITLE
build pipeline failure: NotSerializableException: groovy.json.internal.LazyMap

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/temurin-build#3214]
https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/2222/console
```
11:06:12  an exception which occurred:
11:06:12  	in field Builder.DEFAULTS_JSON
11:06:12  	in object Builder@694bd065
11:06:12  	in field groovy.lang.Closure.delegate
11:06:12  	in object org.jenkinsci.plugins.workflow.cps.CpsClosure2@16639013
11:06:12  	in field groovy.lang.Closure.delegate
11:06:12  	in object org.jenkinsci.plugins.workflow.cps.CpsClosure2@2059a78c
11:06:12  	in field groovy.lang.Closure.delegate
11:06:12  	in object org.jenkinsci.plugins.workflow.cps.CpsClosure2@249d3fd9
11:06:12  	in field groovy.lang.Closure.delegate
11:06:12  	in object org.jenkinsci.plugins.workflow.cps.CpsClosure2@74c6c3d3
11:06:12  	in field groovy.lang.Closure.delegate
11:06:12  	in object org.jenkinsci.plugins.workflow.cps.CpsClosure2@16d94ae
11:06:12  	in field org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.closures
11:06:12  	in object org.jenkinsci.plugins.workflow.cps.CpsThreadGroup@51398533
11:06:12  	in object org.jenkinsci.plugins.workflow.cps.CpsThreadGroup@51398533
11:06:12  Caused: java.io.NotSerializableException: groovy.json.internal.LazyMap
11:06:12  	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:274)
11:06:12  	at org.jboss.marshalling.river.RiverMarshaller.doWriteFields(RiverMarshaller.java:1143)
11:06:12  	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1101)
11:06:12  	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:268)
11:06:12  	at org.jboss.marshalling.river.RiverMarshaller.doWriteFields(RiverMarshaller.java:1143)
11:06:12  	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1101)
11:06:12  	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1080)
11:06:12  	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1080)
11:06:12  	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:268)
11:06:12  	at org.jboss.marshalling.river.RiverMarshaller.doWriteFields(RiverMarshaller.java:1143)
11:06:12  	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1101)
11:06:12  	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1080)
11:06:12  	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1080)
11:06:12  	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:268)
11:06:12  	at org.jboss.marshalling.river.RiverMarshaller.doWriteFields(RiverMarshaller.java:1143)
11:06:12  	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1101)
11:06:12  	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1080)
11:06:12  	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1080)
11:06:12  	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:268)
11:06:12  	at org.jboss.marshalling.river.RiverMarshaller.doWriteFields(RiverMarshaller.java:1143)
11:06:12  	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1101)
11:06:12  	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1080)
11:06:12  	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1080)
11:06:12  	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:268)
11:06:12  	at org.jboss.marshalling.river.RiverMarshaller.doWriteFields(RiverMarshaller.java:1143)
11:06:12  	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1101)
11:06:12  	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1080)
11:06:12  	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1080)
11:06:12  	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:268)
11:06:12  	at org.jboss.marshalling.river.BlockMarshaller.doWriteObject(BlockMarshaller.java:65)
11:06:12  	at org.jboss.marshalling.river.BlockMarshaller.writeObject(BlockMarshaller.java:56)
11:06:12  	at org.jboss.marshalling.MarshallerObjectOutputStream.writeObjectOverride(MarshallerObjectOutputStream.java:50)
11:06:12  	at org.jboss.marshalling.river.RiverObjectOutputStream.writeObjectOverride(RiverObjectOutputStream.java:179)
11:06:12  	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:346)
11:06:12  	at java.base/java.util.HashMap.internalWriteEntries(HashMap.java:1944)
11:06:12  	at java.base/java.util.HashMap.writeObject(HashMap.java:1497)
11:06:12  	at org.jboss.marshalling.reflect.JDKSpecific$SerMethods.callWriteObject(JDKSpecific.java:89)
11:06:12  	at org.jboss.marshalling.reflect.SerializableClass.callWriteObject(SerializableClass.java:199)
11:06:12  	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1089)
11:06:12  	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:268)
11:06:12  	at org.jboss.marshalling.river.RiverMarshaller.doWriteFields(RiverMarshaller.java:1143)
11:06:12  	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1101)
11:06:12  	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:268)
11:06:12  	at org.jboss.marshalling.AbstractObjectOutput.writeObject(AbstractObjectOutput.java:58)
11:06:12  	at org.jboss.marshalling.AbstractMarshaller.writeObject(AbstractMarshaller.java:116)
11:06:12  	at org.jenkinsci.plugins.workflow.support.pickles.serialization.RiverWriter.lambda$writeObject$1(RiverWriter.java:144)
11:06:12  	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox.runInSandbox(GroovySandbox.java:237)
11:06:12  	at org.jenkinsci.plugins.workflow.support.pickles.serialization.RiverWriter.writeObject(RiverWriter.java:143)
11:06:12  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.saveProgram(CpsThreadGroup.java:578)
11:06:12  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.saveProgram(CpsThreadGroup.java:554)
11:06:12  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.saveProgramIfPossible(CpsThreadGroup.java:537)
11:06:12  	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution$9.onSuccess(CpsFlowExecution.java:2063)
11:06:12  	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution$9.onSuccess(CpsFlowExecution.java:2058)
11:06:12  	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution$5$1.run(CpsFlowExecution.java:920)
11:06:12  	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$1.run(CpsVmExecutorService.java:38)
11:06:12  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
11:06:12  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
11:06:12  	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:139)
11:06:12  	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
11:06:12  	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
11:06:12  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
11:06:12  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
11:06:12  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
11:06:12  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
11:06:12  	at java.base/java.lang.Thread.run(Thread.java:833)
[Pipeline] // catchError
Creating placeholder flownodes because failed loading originals.
java.io.IOException: Tried to load head FlowNodes for execution Owner[build-scripts/openjdk11-pipeline/2222:build-scripts/openjdk11-pipeline #2222] but FlowNode was not found in storage for head id:FlowNodeId 99:415
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.initializeStorage(CpsFlowExecution.java:679)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.onLoad(CpsFlowExecution.java:716)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.getExecution(WorkflowRun.java:701)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.onLoad(WorkflowRun.java:560)
	at hudson.model.RunMap.retrieve(RunMap.java:233)
	at hudson.model.RunMap.retrieve(RunMap.java:61)
	at jenkins.model.lazy.AbstractLazyLoadRunMap.load(AbstractLazyLoadRunMap.java:650)
	at jenkins.model.lazy.AbstractLazyLoadRunMap.load(AbstractLazyLoadRunMap.java:632)
	at jenkins.model.lazy.AbstractLazyLoadRunMap.getByNumber(AbstractLazyLoadRunMap.java:530)
	at hudson.model.RunMap.getById(RunMap.java:213)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun$Owner.run(WorkflowRun.java:949)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun$Owner.get(WorkflowRun.java:961)
	at org.jenkinsci.plugins.workflow.flow.FlowExecutionList$1.computeNext(FlowExecutionList.java:76)
	at org.jenkinsci.plugins.workflow.flow.FlowExecutionList$1.computeNext(FlowExecutionList.java:68)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141)
	at org.jenkinsci.plugins.workflow.flow.FlowExecutionList$ItemListenerImpl.onLoaded(FlowExecutionList.java:197)
	at jenkins.model.Jenkins.<init>(Jenkins.java:1036)
	at hudson.model.Hudson.<init>(Hudson.java:86)
	at hudson.model.Hudson.<init>(Hudson.java:82)
	at hudson.WebAppMain$3.run(WebAppMain.java:247)
Finished: FAILURE

```

**Comment by andrew-m-leonard** [comment]
It looks like these happened over the weekend runs, when Jenkins server ran into problems and had to be re-booted... so this error is probably benign.
