### ISSUE TITLE
Implement a new Sign-JSON type job for secure signing of SBOM json using an EF PEM/signService

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/temurin-build#3946]
EPIC https://github.com/adoptium/ci-jenkins-pipelines/issues/610 documents the parts required to implement SBOM json signing.
This issue is to implement the necessary temurin-build/ci-jenkins-pipelines parts to interface with an EF provided signing PEM or "json signing service".

**Comment by Haroon-Khel** [comment]
Work that needs to be done:

https://ci.adoptium.net/job/build-scripts/job/release/job/sign_temurin_jsf/ has been created to replicate https://ci.adoptium.net/job/build-scripts/job/release/job/sign_temurin_gpg/ but to use the PEM format. The sign_temurin_jsf job needs to be updated to use https://github.com/adoptium/temurin-build/blob/master/cyclonedx-lib/sign_src/TemurinSignSBOM.java to sign the SBOM file

Because we dont want the jenkins worker node to build any of the cyclone dx jars, this needs to run in the build scripts during the jdk build, https://github.com/adoptium/temurin-build/blob/62ecfbaeb60cbe5f4072bd81b8d4a3546625dcb2/cyclonedx-lib/build.xml#L68, and then archived, and then pulled onto the jenkins worker node during the sign_temurin_jsf job

**Comment by Haroon-Khel** [comment]
@sxa It looks like the SBOM signing jars can only be built with JDK17+
https://github.com/adoptium/temurin-build/actions/runs/11597199261/job/32290097938?pr=4017

This would make it difficult to build the jars on a build node for platforms like Solaris for example. It should be discussed the feasibility of building the jars on the eclipse signing node

**Comment by andrew-m-leonard** [comment]
> Andrew's idea of [cacheing the cyclone dx](https://github.com/adoptium/infrastructure/issues/3806) dependency jars can be done on the eclipse signing node. Instead of them being downloaded during the ant build step

From chatting with Stewart and Thomas, ideally we don't want to build on the signing node if we can help it. We could add in a "build-sbom-jars-and-sign" job, which builds on any suitable node, and is then used as upstream to the "sign_temurin_jsf" job.

**Comment by Haroon-Khel** [comment]
https://ci.adoptium.net/job/build_sign_sbom_libraries/ is a new jenkins job which will build the signing libraries on a x64 linux node and then archives the jar files. This job will need to be integrated with https://ci.adoptium.net/job/build-scripts/job/release/job/sign_temurin_jsf/

**Comment by Haroon-Khel** [comment]
https://github.com/adoptium/ci-jenkins-pipelines/pull/1131/files is at a state where it kicks off the sign_temurin_jsf job together with the build job. But the signing mechanism is hitting an error
```
+ echo Signing ./workspace/target/OpenJDK21U-sbom_x64_linux_hotspot_2024-12-09-14-54.json
Signing ./workspace/target/OpenJDK21U-sbom_x64_linux_hotspot_2024-12-09-14-54.json
+ java -cp cyclonedx-lib/build/jar/* temurin.sbom.TemurinSignSBOM --verbose --signSBOM --jsonFile ./workspace/target/OpenJDK21U-sbom_x64_linux_hotspot_2024-12-09-14-54.json --privateKeyFile ****
Dec 09, 2024 3:53:31 PM temurin.sbom.TemurinSignSBOM signSBOM
SEVERE: Error signing SBOM
java.io.IOException: Didn't find any: -----BEGIN PRIVATE KEY-----
	at org.webpki.util.PEMDecoder.decodePemObjects(PEMDecoder.java:219)
	at org.webpki.util.PEMDecoder.decodePemObject(PEMDecoder.java:232)
	at org.webpki.util.PEMDecoder.getPrivateKeyBlob(PEMDecoder.java:118)
```
See https://ci.adoptium.net/job/build-scripts/job/release/job/sign_temurin_jsf/19/console

**Comment by Haroon-Khel** [comment]
Update, @sxa has fixed the above error. The key was being stored in an encrypted state, making it difficult for TemurinSignSBOM to read

**Comment by Haroon-Khel** [comment]
https://github.com/adoptium/ci-jenkins-pipelines/pull/1131 and https://github.com/adoptium/temurin-build/pull/4094 are ready to be merged

**Comment by Haroon-Khel** [comment]
The above prs were merged
